
ccflags-y := -Idrivers/staging/omaprdrm
omap_rpc-y := omap_rpc_htable.o \
              omap_rpc_dmabuf.o \
              omap_rpc_ion.o \
              omap_rpc_rproc.o

obj-$(CONFIG_RPC_OMAP)	+= omap_rpc.o

