#
# Makefile for the Linux kernel ubuntu supplied third-party device drivers.
#

##
##
##
obj-$(CONFIG_BLK_DEV_COMPCACHE)	+= compcache/
##
##
##
obj-$(CONFIG_DM_RAID45)		+= dm-raid4-5/
##
##
##
##
##
##

# This is a stupid trick to get kbuild to create ubuntu/built-in.o
obj- += foo.o
